#!/bin/bash
# Initialises the git store so that it can be populated with emails

usage() {
  cat <<\EOF
git-kv-init -d <store-path>
EOF
exit 1
}

while [ ! $# == 0 ]; do
  case $1 in
  -d)
      GIT_DIR=$2 ;
      shift; shift; 
  ;;
  *) echo Unknown option $1 ; usage ;;
  esac
done

GIT_DIR=${GIT_DIR:-~/.git-kv} git init
