#!/bin/bash -ex
# Initialises the git store so that it can be populated with emails

usage() {
  cat <<\EOF
git-kv-put -d <store-path> [key1] [key2]
EOF
exit 1
}

while [ ! $# == 0 ]; do
  case $1 in
  -d)
      GIT_DIR=$1 ;
      shift; shift;
  ;;
  -h) usage ;;
  *)
    KEYS="$1 $KEYS"
    shift
  ;;
  esac
done

if [ "X$KEYS" = X ]; then
  usage
fi

export GIT_DIR=${GIT_DIR:-~/.git-kv}
HASH=`git hash-object -w --stdin`
for KEY in $KEYS; do
  git update-index --add --cacheinfo 100644,$HASH,$KEY
done
