#!/bin/bash
# Initialises the git store so that it can be populated with emails

while [ ! $# == 0 ]; do
  case $0 in
  -d)
      GIT_DIR=$1 ;
      shift; shift; 
  ;;
  *) echo Unknown option $0 ; exit 1 ;;
  esac
done

GIT_DIR=${GIT_DIR:-~/.git-mail} git init
